# Used by "mix format"
#
# lib/onnx is protox output, regenerated by `mix generate_protobuf`, and it does not survive
# a formatter pass: all 24 files fail --check-formatted, and reformatting them only holds
# until the next generation. Excluding generated code is the difference between a format gate
# that means something and one that is permanently red for a reason nobody can fix.
[
  inputs:
    Enum.flat_map(
      ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
      &Path.wildcard(&1, match_dot: true)
    ) -- Path.wildcard("lib/onnx/**/*.{ex,exs}")
]
